### ISSUE TITLE
TypeError: no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by mmhan** [tylerhunt/rack-canonical-host#52]
Got this error while in development. Not sure if that's a bug or if I'm doing something wrong.

Ruby 2.3.1
Rack 2.0.3

```
2017-08-23 15:00:50 +0630: Rack app error handling request { GET / }
#<TypeError: no implicit conversion from nil to integer>
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:46:in `[]'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:46:in `block in any_match?'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:46:in `any?'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:46:in `any_match?'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:68:in `ignored?'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:28:in `canonical?'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host.rb:18:in `call'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/Users/mmhan/.rvm/gems/ruby-2.3.1@mmcdb/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mmhan** [comment]
Just found that it's the result of one of the `ignore:` array elements was nil in certain conditions. Closing this issue.
